version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=7137476088:AAG2GrP94NS5PredenfFEn5NdkJ--INed9E
    volumes:
      - .:/app
    restart: always

volumes:
  data:
